version: '3'
tasks:
  up:
    desc: Start all services with Docker Compose
    cmds:
      - docker-compose up --build -d

  subscribe:broker:
    desc: Subscribe to 'colour.generated' events on the event broker
    cmds:
      - docker run --rm -it --network outcome-app-pattern_default natsio/nats-box:latest nats sub -s nats://event-hub:4222 colour.generated

  lint:asyncapi:
    desc: Lint the AsyncAPI contract (requires asyncapi CLI)
    cmds:
      - npx -y @asyncapi/cli@latest validate contracts/api/behaviour-service.asyncapi.yaml

  lint:datacontract:
    desc: Lint the data contract (requires datacontract CLI)
    cmds:
      - python3 -m pip install 'datacontract-cli' && datacontract lint contracts/data/data-product.contract.yaml

  lint:all:
    desc: Lint both the AsyncAPI and data contracts
    deps: [lint:asyncapi, lint:datacontract]

  test:unit:
    desc: Run all Python tests
    cmds:
      - PYTHONPATH=. pytest behaviour/tests/unit

  test:integration:
    desc: Run all Python tests
    cmds:
      - docker compose up --build contract-test

  run:api:
    desc: Run the FastAPI behaviour service locally
    dir: behaviour/src
    cmds:
      - uvicorn main:app --reload --host 0.0.0.0 --port 8000

  post:api:
    desc: Perform a simple POST request to the /generate-colour endpoint
    cmds:
      - curl -X POST http://localhost:8000/generate-colour

  ci: 
    desc: Run all continuous integration tasks
    deps: [lint:all]